name: Build and Publish image

on:
  push:
    branches:
    - "main"

jobs:
  release-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.B_TOKEN }}
        tag_prefix: ""
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Docker
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/wordpress-prod:${{ steps.tag_version.outputs.new_tag }}
    
    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    - name: Test manifests
      continue-on-error: true
      uses: instrumenta/kubeval-action@master
      with: 
       files: ./chart/wordpress/templates

    - name: Helm Package
      run: |
        cd chart
        helm package wordpress --version=${{ steps.tag_version.outputs.new_tag }} --app-version=${{ steps.tag_version.outputs.new_tag }}
        cd ..
        helm repo index --url https://github.com/S-Stepanenko/project/ --merge index.yaml .

    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generated by GitHub Action. ${{ steps.tag_version.outputs.new_tag }}"
        git push origin main

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: s-stepanenko_notifications
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Kubeval checks
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}   